const fs = require('fs');
let f = fs.readFileSync('public/index.html', 'utf8');

// 9a: Add F and B key handlers to the additional keybinds section
const old9a = "  // C = collect artifact\r\n  if (e.key === 'c' || e.key === 'C') {\r\n    if (state.inAltUniverse) collectArtifact();\r\n  }\r\n});";
const rep9a = "  // C = collect artifact\r\n  if (e.key === 'c' || e.key === 'C') {\r\n    if (state.inAltUniverse) collectArtifact();\r\n  }\r\n  // F = warp (open star map)\r\n  if (e.key === 'f' || e.key === 'F') {\r\n    showScreen('starmap');\r\n  }\r\n  // B = dock at station\r\n  if (e.key === 'b' || e.key === 'B') {\r\n    const sys = state.starSystems[state.location.systemIndex];\r\n    if (sys && sys.hasStation) { state.location.docked = true; showScreen('station'); }\r\n    else addComms('System', 'No station in this system.');\r\n  }\r\n});";
if (f.includes(old9a)) { f = f.replace(old9a, rep9a); console.log('PATCH9a APPLIED'); }
else console.log('PATCH9a FAILED');

// 9b: Add action bar click handlers (before "// Title buttons")
const old9b = "// Title buttons\r\ndocument.getElementById('btn-new').addEventListener('click', () => { initCreateScreen(); showScreen('create'); });";
const rep9b = `// Action bar click handlers (mirror keyboard shortcuts for mouse/touch users)\r\ndocument.querySelectorAll('#action-bar .action-btn').forEach(btn => {\r\n  btn.addEventListener('click', (ev) => {\r\n    ev.stopPropagation();\r\n    if (!c.active) return;\r\n    const action = btn.dataset.action;\r\n    if (action === 'mine') { if (state.mining.active) stopMining(); else if (c.asteroids.length > 0) startMining(0); }\r\n    else if (action === 'chat') { const panel = document.getElementById('chatbot-panel'); panel.classList.toggle('open'); state.chatbot.visible = panel.classList.contains('open'); if (state.chatbot.visible) { if (document.pointerLockElement) document.exitPointerLock(); setTimeout(() => document.getElementById('chatbot-input').focus(), 100); } }\r\n    else if (action === 'skins') { document.getElementById('skin-panel').classList.toggle('open'); }\r\n    else if (action === 'gate') { if (stargateGroup && ship.position.distanceTo(stargateGroup.position) < 40) { if (state.inAltUniverse) exitAltUniverse(); else enterAltUniverse(); } else addComms('System', 'No stargate in range.'); }\r\n    else if (action === 'collect') { if (state.inAltUniverse) collectArtifact(); }\r\n    else if (action === 'reload') { if (c.ammo < c.maxAmmo && !c._reloading) { c._reloading = true; c.weaponReady = false; addComms('System', 'Reloading...'); setTimeout(() => { c.ammo = c.maxAmmo; c._reloading = false; c.weaponReady = true; AudioSFX.play('quest_complete'); addComms('System', 'Ammo replenished.'); }, 1500); } }\r\n    else if (action === 'warp') { showScreen('starmap'); }\r\n    else if (action === 'dock') { const sys = state.starSystems[state.location.systemIndex]; if (sys && sys.hasStation) { state.location.docked = true; showScreen('station'); } else addComms('System', 'No station in this system.'); }\r\n  });\r\n});\r\n\r\n// Title buttons\r\ndocument.getElementById('btn-new').addEventListener('click', () => { initCreateScreen(); showScreen('create'); });`;
if (f.includes(old9b)) { f = f.replace(old9b, rep9b); console.log('PATCH9b APPLIED'); }
else console.log('PATCH9b FAILED');

// 9c: Add mobile touch controls (after canvas touchstart handler, before pointerlockchange)
const old9c = "    lastTapTime = now;\r\n  }\r\n});\r\n\r\ndocument.addEventListener('pointerlockchange', () => {";
const rep9c = `    lastTapTime = now;\r\n  }\r\n});\r\n\r\n// Mobile touch controls: virtual joystick, fire, reload\r\n(function initMobileControls() {\r\n  const moveZone = document.getElementById('touch-move-zone');\r\n  const stick = document.getElementById('touch-stick');\r\n  const fireBtn = document.getElementById('touch-fire');\r\n  const reloadBtn = document.getElementById('touch-reload');\r\n  let touchOrigin = null, touchId = null;\r\n  moveZone.addEventListener('touchstart', (e) => {\r\n    e.preventDefault();\r\n    const t = e.changedTouches[0];\r\n    touchOrigin = { x: t.clientX, y: t.clientY };\r\n    touchId = t.identifier;\r\n    stick.style.opacity = '1';\r\n  }, { passive: false });\r\n  moveZone.addEventListener('touchmove', (e) => {\r\n    e.preventDefault();\r\n    if (!touchOrigin) return;\r\n    for (const t of e.changedTouches) {\r\n      if (t.identifier !== touchId) continue;\r\n      const dx = t.clientX - touchOrigin.x;\r\n      const dy = t.clientY - touchOrigin.y;\r\n      const maxR = 40;\r\n      const dist = Math.min(Math.sqrt(dx * dx + dy * dy), maxR);\r\n      const angle = Math.atan2(dy, dx);\r\n      const nx = Math.cos(angle) * dist;\r\n      const ny = Math.sin(angle) * dist;\r\n      stick.style.transform = \u0060translate(\${nx}px, \${ny}px)\u0060;\r\n      state.flight.thrust = -(ny / maxR);\r\n      state.flight.strafe = nx / maxR;\r\n    }\r\n  }, { passive: false });\r\n  const endTouch = () => {\r\n    touchOrigin = null; touchId = null;\r\n    stick.style.transform = 'translate(0,0)';\r\n    stick.style.opacity = '0.5';\r\n    state.flight.thrust = 0;\r\n    state.flight.strafe = 0;\r\n  };\r\n  moveZone.addEventListener('touchend', endTouch);\r\n  moveZone.addEventListener('touchcancel', endTouch);\r\n  let fireInterval = null;\r\n  fireBtn.addEventListener('touchstart', (e) => {\r\n    e.preventDefault();\r\n    if (c.active && typeof fireWeapon === 'function') fireWeapon();\r\n    fireInterval = setInterval(() => { if (c.active && typeof fireWeapon === 'function') fireWeapon(); }, 200);\r\n  }, { passive: false });\r\n  fireBtn.addEventListener('touchend', () => { clearInterval(fireInterval); fireInterval = null; });\r\n  fireBtn.addEventListener('touchcancel', () => { clearInterval(fireInterval); fireInterval = null; });\r\n  reloadBtn.addEventListener('touchstart', (e) => {\r\n    e.preventDefault();\r\n    if (c.active && c.ammo < c.maxAmmo && !c._reloading) {\r\n      c._reloading = true; c.weaponReady = false;\r\n      addComms('System', 'Reloading...');\r\n      setTimeout(() => { c.ammo = c.maxAmmo; c._reloading = false; c.weaponReady = true; AudioSFX.play('quest_complete'); addComms('System', 'Ammo replenished.'); }, 1500);\r\n    }\r\n  }, { passive: false });\r\n})();\r\n\r\ndocument.addEventListener('pointerlockchange', () => {`;
if (f.includes(old9c)) { f = f.replace(old9c, rep9c); console.log('PATCH9c APPLIED'); }
else console.log('PATCH9c FAILED');

fs.writeFileSync('public/index.html', f);
